#!/bin/bash

if command -v ctags &> /dev/null; then
  set -e
  PATH="/usr/local/bin:$PATH"
  dir="`git rev-parse --show-toplevel`"
  trap 'rm -f "$dir/$$.tags"' EXIT

  # Generate tags
  git ls-files | \
    ctags --tag-relative=yes -L - -f"$dir/$$.tags" --languages=-javascript,sql

  mv "$dir/$$.tags" "$dir/tags"
fi
