#Requires -Version 7
<#
.SYNOPSIS
    Install dotfiles on Windows.

.DESCRIPTION
    Creates junctions, stubs, or copies to wire the dotfiles repo into the
    correct OS locations. Safe to re-run — existing targets are backed up
    before being replaced.

.PARAMETER Module
    One or more modules to install: neovim, vim, powershell, git, bash, tig, tmux, curl, all.

.PARAMETER DryRun
    Preview what would happen without making any changes.

.EXAMPLE
    .\setup.ps1 -Module neovim,powershell
    .\setup.ps1 -Module git
    .\setup.ps1 -Module all -DryRun
#>
param(
    [Parameter(Mandatory)]
    [string[]] $Module,

    [switch] $DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Dotfiles = $PSScriptRoot

# Expand 'all'
if ($Module -contains 'all') {
    $Module = @('neovim', 'vim', 'powershell', 'git', 'bash', 'tig', 'tmux', 'zellij', 'curl', 'claude', 'lazygit', 'windowsterminal', 'bat', 'vscode', 'winget')
}
$Module = $Module | Select-Object -Unique

# ── Output helpers ────────────────────────────────────────────────────────────

function Write-Info    ($Msg) { Write-Host "[INFO]  $Msg" -ForegroundColor Cyan    }
function Write-Ok      ($Msg) { Write-Host "[OK]    $Msg" -ForegroundColor Green   }
function Write-Warn    ($Msg) { Write-Host "[WARN]  $Msg" -ForegroundColor Yellow  }
function Write-Fail    ($Msg) { Write-Host "[ERROR] $Msg" -ForegroundColor Red     }

# ── Core helpers ──────────────────────────────────────────────────────────────

function Backup-Existing ([string]$Path) {
    if (-not (Test-Path $Path)) { return }
    $ts     = Get-Date -Format 'yyyyMMdd_HHmmss'
    $backup = "${Path}.bak.${ts}"
    if (-not $DryRun) { Move-Item -Path $Path -Destination $backup }
    Write-Warn "Backed up:  $Path"
    Write-Warn "        ->  $backup"
}

# Directory junction — works cross-volume, no elevation required.
function New-Junction ([string]$Link, [string]$Target) {
    if (-not (Test-Path $Target -PathType Container)) {
        Write-Fail "Source directory not found: $Target"; return
    }
    if ($DryRun) { Write-Info "[DRY RUN] junction $Link -> $Target"; return }

    Backup-Existing $Link
    New-Item -ItemType Junction -Path $Link -Target $Target | Out-Null
    Write-Ok "Junction:   $Link"
    Write-Ok "         -> $Target"
}

# File copy — simple, always works cross-volume.
# Re-run the installer to pick up changes from the repo.
function Copy-Dotfile ([string]$Dest, [string]$Source) {
    if (-not (Test-Path $Source)) {
        Write-Fail "Source file not found: $Source"; return
    }
    $dir = Split-Path $Dest
    if (-not (Test-Path $dir)) {
        if (-not $DryRun) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Write-Info "Created:    $dir"
    }
    if ($DryRun) { Write-Info "[DRY RUN] copy $Source -> $Dest"; return }

    Backup-Existing $Dest
    Copy-Item -Path $Source -Destination $Dest -Force
    Write-Ok "Copied:     $Dest"
    Write-Warn "(Re-run setup.ps1 after editing this file in the repo)"
}

# Generated stub — sources the real PS file from the repo path.
# Changes to the repo file are live immediately; no elevation needed.
function New-SourceStub ([string]$StubPath, [string]$RealSource) {
    if (-not (Test-Path $RealSource)) {
        Write-Fail "Source file not found: $RealSource"; return
    }
    $dir = Split-Path $StubPath
    if (-not (Test-Path $dir)) {
        if (-not $DryRun) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Write-Info "Created:    $dir"
    }
    $content = @"
# Auto-generated by setup.ps1 — do not edit directly.
# Edit the source file in the dotfiles repo and re-run setup.ps1 if the path changes.
. '$RealSource'
"@
    if ($DryRun) { Write-Info "[DRY RUN] stub $StubPath -> $RealSource"; return }

    Backup-Existing $StubPath
    Set-Content -Path $StubPath -Value $content -Encoding UTF8
    Write-Ok "Stub:       $StubPath"
    Write-Ok "         -> $RealSource"
}

# Git [include] stub — installs a gitconfig that includes the real file from the
# repo via git's native include mechanism. Works cross-volume; changes are live.
function New-GitIncludeStub ([string]$StubPath, [string]$RealSource) {
    if (-not (Test-Path $RealSource)) {
        Write-Fail "Source file not found: $RealSource"; return
    }
    $dir = Split-Path $StubPath
    if (-not (Test-Path $dir)) {
        if (-not $DryRun) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Write-Info "Created:    $dir"
    }
    # Git config paths use forward slashes on all platforms.
    $fwdSlashSource = $RealSource.Replace('\', '/')
    $content = @"
; Auto-generated by setup.ps1 — do not edit directly.
; Edit the source file in the dotfiles repo.
[include]
    path = $fwdSlashSource
"@
    if ($DryRun) { Write-Info "[DRY RUN] git-include stub $StubPath -> $RealSource"; return }

    Backup-Existing $StubPath
    Set-Content -Path $StubPath -Value $content -Encoding UTF8
    Write-Ok "Git stub:   $StubPath"
    Write-Ok "         -> $RealSource"
}

# ── Modules ───────────────────────────────────────────────────────────────────

function Install-Git {
    Write-Host ''
    Write-Info '=== Git ==='

    # ~/.gitconfig — stub that [include]s the repo file; cross-volume, always live.
    New-GitIncludeStub `
        -StubPath  (Join-Path $env:USERPROFILE '.gitconfig') `
        -RealSource (Join-Path $Dotfiles 'git\gitconfig')

    # ~/.gitconfig-work — referenced by [includeIf] inside gitconfig.
    New-GitIncludeStub `
        -StubPath  (Join-Path $env:USERPROFILE '.gitconfig-work') `
        -RealSource (Join-Path $Dotfiles 'git\gitconfig-work')

    # ~/.gitignore — global ignore file.
    New-GitIncludeStub `
        -StubPath  (Join-Path $env:USERPROFILE '.gitignore') `
        -RealSource (Join-Path $Dotfiles 'git\gitignore')

    # ~/.gitignore-work — extra ignore patterns for work repos (overrides core.excludesFile via gitconfig-work).
    New-GitIncludeStub `
        -StubPath  (Join-Path $env:USERPROFILE '.gitignore-work') `
        -RealSource (Join-Path $Dotfiles 'git\gitignore-work')

    # ~/.gitmessage — commit message template.
    Copy-Dotfile `
        -Dest   (Join-Path $env:USERPROFILE '.gitmessage') `
        -Source (Join-Path $Dotfiles 'git\gitmessage')

    # ~/.git_templates — hooks directory (init.templatedir + core.hooksPath).
    New-Junction `
        -Link   (Join-Path $env:USERPROFILE '.git_templates') `
        -Target (Join-Path $Dotfiles 'git\templates')
}

function Install-Neovim {
    Write-Host ''
    Write-Info '=== Neovim ==='
    # Honour XDG_CONFIG_HOME if set (the PowerShell profile exports it as ~/.config).
    $configBase = if ($env:XDG_CONFIG_HOME) { $env:XDG_CONFIG_HOME } else { $env:LOCALAPPDATA }
    New-Junction `
        -Link   (Join-Path $configBase 'nvim') `
        -Target (Join-Path $Dotfiles 'nvim')
}

function Install-Vim {
    Write-Host ''
    Write-Info '=== Vim ==='
    # vimrc lives inside vim/ so Vim finds it at ~/vimfiles/vimrc automatically.
    New-Junction `
        -Link   (Join-Path $env:USERPROFILE 'vimfiles') `
        -Target (Join-Path $Dotfiles 'vim')
}

function Install-PowerShell {
    Write-Host ''
    Write-Info '=== PowerShell ==='

    $profileSource = Join-Path $Dotfiles 'powershell\Microsoft.PowerShell_profile.ps1'
    $docs = [Environment]::GetFolderPath('MyDocuments')

    # Stub into PS7, PS5, and VSCode locations — all source the same repo file
    $profileTargets = @(
        (Join-Path $docs 'PowerShell\Microsoft.PowerShell_profile.ps1'),        # PS7
        (Join-Path $docs 'WindowsPowerShell\Microsoft.PowerShell_profile.ps1'), # PS5
        (Join-Path $docs 'WindowsPowerShell\Microsoft.VSCode_profile.ps1')      # VSCode
    )
    foreach ($target in $profileTargets) {
        New-SourceStub -StubPath $target -RealSource $profileSource
    }

    # Junction the Profile\ subdirectory (contains Set-Prompt.ps1)
    $profileDirSrc  = Join-Path $Dotfiles 'powershell\Profile'
    $profileDirDest = Join-Path $docs 'PowerShell\Profile'
    if (Test-Path $profileDirSrc -PathType Container) {
        New-Junction -Link $profileDirDest -Target $profileDirSrc
    }
}

function Install-Bash {
    Write-Host ''
    Write-Info '=== Bash ==='
    Write-Warn 'Bash module is Linux/WSL only — skipping on Windows.'
}

function Install-Tig {
    Write-Host ''
    Write-Info '=== Tig ==='
    Copy-Dotfile `
        -Dest   (Join-Path $env:USERPROFILE '.tigrc') `
        -Source (Join-Path $Dotfiles 'tig\tigrc')
    Copy-Dotfile `
        -Dest   (Join-Path $env:USERPROFILE '.tigrc.vim') `
        -Source (Join-Path $Dotfiles 'tig\tigrc.vim')
}

function Install-Tmux {
    Write-Host ''
    Write-Info '=== Tmux ==='
    Write-Warn 'Tmux module is Linux/WSL only — skipping on Windows.'
}

function Install-Zellij {
    Write-Host ''
    Write-Info '=== Zellij ==='
    # Windows-native path: %APPDATA%\Zellij\config\ (https://zellij.dev/documentation/configuration.html)
    # Zellij does not document XDG support on Windows, so we always use APPDATA here.
    $zellijConfig = Join-Path $env:APPDATA 'Zellij\config'
    $zellijParent = Join-Path $env:APPDATA 'Zellij'
    if (-not (Test-Path $zellijParent) -and -not $DryRun) {
        New-Item -ItemType Directory -Path $zellijParent -Force | Out-Null
        Write-Info "Created:    $zellijParent"
    }
    New-Junction `
        -Link   $zellijConfig `
        -Target (Join-Path $Dotfiles 'zellij')
}

function Install-Curl {
    Write-Host ''
    Write-Info '=== Curl ==='
    Copy-Dotfile `
        -Dest   (Join-Path $env:USERPROFILE '.curlrc') `
        -Source (Join-Path $Dotfiles 'curl\curlrc')
}

function Install-WindowsTerminal {
    Write-Host ''
    Write-Info '=== Windows Terminal ==='
    $wtState = Join-Path $env:LOCALAPPDATA 'Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState'
    if (-not (Test-Path $wtState)) {
        Write-Warn 'Windows Terminal not found — skipping.'
        return
    }
    Copy-Dotfile `
        -Dest   (Join-Path $wtState 'settings.json') `
        -Source (Join-Path $Dotfiles 'windowsterminal\settings.json')
}

function Install-Lazygit {
    Write-Host ''
    Write-Info '=== Lazygit ==='
    Write-Info 'Config is loaded via $env:LG_CONFIG_FILE set in the PowerShell profile — no files to copy.'
    Write-Info "Base:  $(Join-Path $Dotfiles 'lazygit\config.yml')"
    Write-Info "Theme: lazygit\theme-mocha.yml or theme-latte.yml (selected at profile load from OS theme)"
    if (-not (Get-Command -Name lazygit -ErrorAction Ignore)) {
        Write-Warn 'lazygit not found. Install with: winget install JesseDuffield.lazygit'
    } else {
        Write-Ok 'lazygit is installed.'
    }
}

function Install-Winget {
    Write-Host ''
    Write-Info '=== winget packages ==='
    Write-Info 'Run the bootstrap script to install curated packages on a new machine:'
    Write-Info "  $(Join-Path $Dotfiles 'winget\packages.ps1') [-DryRun]"
    Write-Info 'Or use winget import:'
    Write-Info "  winget import -i $(Join-Path $Dotfiles 'winget\packages.json') --ignore-unavailable"
}

function Install-VSCode {
    Write-Host ''
    Write-Info '=== VSCode ==='
    Write-Info 'Settings are managed by VSCode Settings Sync — no files to copy.'
    Write-Info "Reference snapshot: $(Join-Path $Dotfiles 'vscode\settings.json')"
    Write-Info 'Machine-specific settings (not synced) must be configured locally:'
    Write-Info '  vscode-neovim.neovimExecutablePaths.win32'
    Write-Info '  powershell.powerShellAdditionalExePaths'
    Write-Info '  dotnetAcquisitionExtension.existingDotnetPath'
    Write-Info '  dev.containers.dockerPath'
    Write-Info '  mssql.connections / mssql.connectionGroups'
    Write-Info '  github-actions.use-enterprise'
    if (-not (Get-Command -Name code -ErrorAction Ignore)) {
        Write-Warn 'VSCode not found in PATH. Install from https://code.visualstudio.com/'
    } else {
        Write-Ok 'VSCode is installed.'
    }
}

function Install-Bat {
    Write-Host ''
    Write-Info '=== bat ==='
    Write-Info 'Config is loaded via $env:BAT_CONFIG_PATH set in the PowerShell profile — no files to copy.'
    Write-Info "Config: $(Join-Path $Dotfiles 'bat\config')"
    if (-not (Get-Command -Name bat -ErrorAction Ignore)) {
        Write-Warn 'bat not found. Install with: winget install sharkdp.bat'
    } else {
        Write-Ok 'bat is installed.'
    }
}

function Install-Claude {
    Write-Host ''
    Write-Info '=== Claude Code ==='
    $claudeDir = Join-Path $env:USERPROFILE '.claude'
    Copy-Dotfile `
        -Dest   (Join-Path $claudeDir 'settings.json') `
        -Source (Join-Path $Dotfiles 'claude\settings.json')
    Copy-Dotfile `
        -Dest   (Join-Path $claudeDir 'statusline-command.sh') `
        -Source (Join-Path $Dotfiles 'claude\statusline-command.sh')

    # Skills — junction each subdirectory into ~/.claude/skills/
    $skillsSrc = Join-Path $Dotfiles 'claude\skills'
    $skillsDst = Join-Path $claudeDir 'skills'
    if (-not (Test-Path $skillsDst)) {
        if (-not $DryRun) { New-Item -ItemType Directory -Path $skillsDst -Force | Out-Null }
        Write-Info "Created:    $skillsDst"
    }
    $skills = Get-ChildItem -Path $skillsSrc -Directory -ErrorAction SilentlyContinue
    if ($skills) {
        foreach ($skill in $skills) {
            New-Junction -Link (Join-Path $skillsDst $skill.Name) -Target $skill.FullName
        }
    } else {
        Write-Info 'No skills to install (claude/skills/ is empty).'
    }
}

# ── Main ─────────────────────────────────────────────────────────────────────

if ($DryRun) { Write-Warn 'DRY RUN — no changes will be made.' }

foreach ($m in $Module) {
    switch ($m) {
        'neovim'     { Install-Neovim     }
        'vim'        { Install-Vim        }
        'powershell' { Install-PowerShell }
        'git'        { Install-Git        }
        'bash'       { Install-Bash       }
        'tig'        { Install-Tig        }
        'tmux'       { Install-Tmux       }
        'zellij'     { Install-Zellij     }
        'curl'       { Install-Curl       }
        'winget'     { Install-Winget     }
        'vscode'     { Install-VSCode     }
        'bat'        { Install-Bat        }
        'claude'     { Install-Claude     }
        'lazygit'        { Install-Lazygit        }
        'windowsterminal' { Install-WindowsTerminal }
        default          { Write-Warn "Unknown module '$m' — skipping." }
    }
}

Write-Host ''
Write-Ok 'Done.'
