#Requires -Version 7
<#
.SYNOPSIS
    Install dotfiles on Windows.

.DESCRIPTION
    Creates junctions, stubs, or copies to wire the dotfiles repo into the
    correct OS locations. Safe to re-run — existing targets are backed up
    before being replaced.

.PARAMETER Module
    One or more modules to install: neovim, vim, powershell, all.

.PARAMETER DryRun
    Preview what would happen without making any changes.

.EXAMPLE
    .\setup.ps1 -Module neovim,powershell
    .\setup.ps1 -Module all -DryRun
#>
param(
    [Parameter(Mandatory)]
    [string[]] $Module,

    [switch] $DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Dotfiles = $PSScriptRoot

# Expand 'all'
if ($Module -contains 'all') { $Module = @('neovim', 'vim', 'powershell') }
$Module = $Module | Select-Object -Unique

# ── Output helpers ────────────────────────────────────────────────────────────

function Write-Info    ($Msg) { Write-Host "[INFO]  $Msg" -ForegroundColor Cyan    }
function Write-Ok      ($Msg) { Write-Host "[OK]    $Msg" -ForegroundColor Green   }
function Write-Warn    ($Msg) { Write-Host "[WARN]  $Msg" -ForegroundColor Yellow  }
function Write-Fail    ($Msg) { Write-Host "[ERROR] $Msg" -ForegroundColor Red     }

# ── Core helpers ──────────────────────────────────────────────────────────────

function Backup-Existing ([string]$Path) {
    if (-not (Test-Path $Path)) { return }
    $ts     = Get-Date -Format 'yyyyMMdd_HHmmss'
    $backup = "${Path}.bak.${ts}"
    if (-not $DryRun) { Move-Item -Path $Path -Destination $backup }
    Write-Warn "Backed up:  $Path"
    Write-Warn "        ->  $backup"
}

# Directory junction — works cross-volume, no elevation required.
function New-Junction ([string]$Link, [string]$Target) {
    if (-not (Test-Path $Target -PathType Container)) {
        Write-Fail "Source directory not found: $Target"; return
    }
    if ($DryRun) { Write-Info "[DRY RUN] junction $Link -> $Target"; return }

    Backup-Existing $Link
    New-Item -ItemType Junction -Path $Link -Target $Target | Out-Null
    Write-Ok "Junction:   $Link"
    Write-Ok "         -> $Target"
}

# File copy — simple, always works cross-volume.
# Re-run the installer to pick up changes from the repo.
function Copy-Dotfile ([string]$Dest, [string]$Source) {
    if (-not (Test-Path $Source)) {
        Write-Fail "Source file not found: $Source"; return
    }
    $dir = Split-Path $Dest
    if (-not (Test-Path $dir)) {
        if (-not $DryRun) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Write-Info "Created:    $dir"
    }
    if ($DryRun) { Write-Info "[DRY RUN] copy $Source -> $Dest"; return }

    Backup-Existing $Dest
    Copy-Item -Path $Source -Destination $Dest -Force
    Write-Ok "Copied:     $Dest"
    Write-Warn "(Re-run setup.ps1 after editing this file in the repo)"
}

# Generated stub — sources the real file from the repo path.
# Changes to the repo file are live immediately; no elevation needed.
function New-SourceStub ([string]$StubPath, [string]$RealSource) {
    if (-not (Test-Path $RealSource)) {
        Write-Fail "Source file not found: $RealSource"; return
    }
    $dir = Split-Path $StubPath
    if (-not (Test-Path $dir)) {
        if (-not $DryRun) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Write-Info "Created:    $dir"
    }
    $content = @"
# Auto-generated by setup.ps1 — do not edit directly.
# Edit the source file in the dotfiles repo and re-run setup.ps1 if the path changes.
. '$RealSource'
"@
    if ($DryRun) { Write-Info "[DRY RUN] stub $StubPath -> $RealSource"; return }

    Backup-Existing $StubPath
    Set-Content -Path $StubPath -Value $content -Encoding UTF8
    Write-Ok "Stub:       $StubPath"
    Write-Ok "         -> $RealSource"
}

# ── Modules ───────────────────────────────────────────────────────────────────

function Install-Neovim {
    Write-Host ''
    Write-Info '=== Neovim ==='
    $source = Join-Path $Dotfiles 'config\nvim'
    $target = Join-Path $env:LOCALAPPDATA 'nvim'
    New-Junction -Link $target -Target $source
}

function Install-Vim {
    Write-Host ''
    Write-Info '=== Vim ==='

    # _vimrc — copy (file, potentially cross-volume)
    $vimrcSrc  = Join-Path $Dotfiles 'vimrc'
    $vimrcDest = Join-Path $env:USERPROFILE '_vimrc'
    Copy-Dotfile -Dest $vimrcDest -Source $vimrcSrc

    # vimfiles — junction (directory, cross-volume works)
    $vimDirSrc  = Join-Path $Dotfiles 'vim'
    $vimDirDest = Join-Path $env:USERPROFILE 'vimfiles'
    New-Junction -Link $vimDirDest -Target $vimDirSrc
}

function Install-PowerShell {
    Write-Host ''
    Write-Info '=== PowerShell ==='

    $hostname      = $env:COMPUTERNAME
    $profileSource = Join-Path $Dotfiles "Documents\PowerShell\Microsoft.PowerShell_profile.$hostname.ps1"

    if (-not (Test-Path $profileSource)) {
        Write-Warn "No machine-specific profile found for '$hostname'."
        Write-Warn "Expected: $profileSource"
        Write-Warn "Create that file in the repo and re-run to install."
        return
    }

    $docs = [Environment]::GetFolderPath('MyDocuments')

    # Stub the profile into all three PS locations
    $profileTargets = @(
        Join-Path $docs 'PowerShell\Microsoft.PowerShell_profile.ps1',        # PS7
        Join-Path $docs 'WindowsPowerShell\Microsoft.PowerShell_profile.ps1', # PS5
        Join-Path $docs 'WindowsPowerShell\Microsoft.VSCode_profile.ps1'      # VSCode
    )
    foreach ($target in $profileTargets) {
        New-SourceStub -StubPath $target -RealSource $profileSource
    }

    # Junction the Profile\ subdirectory (contains Set-Prompt.ps1)
    $profileDirSrc  = Join-Path $Dotfiles 'Documents\PowerShell\Profile'
    $profileDirDest = Join-Path $docs 'PowerShell\Profile'
    if (Test-Path $profileDirSrc -PathType Container) {
        New-Junction -Link $profileDirDest -Target $profileDirSrc
    }
}

# ── Main ─────────────────────────────────────────────────────────────────────

if ($DryRun) { Write-Warn 'DRY RUN — no changes will be made.' }

foreach ($m in $Module) {
    switch ($m) {
        'neovim'     { Install-Neovim     }
        'vim'        { Install-Vim        }
        'powershell' { Install-PowerShell }
        default      { Write-Warn "Unknown module '$m' — skipping." }
    }
}

Write-Host ''
Write-Ok 'Done.'
