#!/bin/sh

#  pc icon
#  (9 squares icon)
#  (pdf icon)
#  (1 cog settings icon)

ws1=  # term icon
ws2=  # web icon
ws3=  # mail icon
ws4=  # code icon
ws5=  # math [infinity] icon
ws6=  # media icon
ws7=  # misc icon
ws8=  # notes/docs icon
ws9=  # settings icon
ws10= # shield icon

bspc config border_width          5
bspc config window_gap            5
bspc config focus_follows_pointer true
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true

bspc config focused_border_color  \#FFFFFF
bspc config presel_feedback_color \#586E75

bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws10

bspc config -d $ws1 window_gap 15

bspc desktop $ws2 -l monocle
bspc desktop $ws3 -l monocle
bspc desktop $ws10 -l monocle

bspc rule -a Firefox desktop=^2
bspc rule -a qutebrowser desktop=^2

bspc rule -a Thunderbird desktop=^3
bspc rule -a Trello:trello desktop=^3 follow=on

bspc rule -a streamlink-twitch-gui desktop=^4

bspc rule -a Vlc desktop=^5
bspc rule -a mpv desktop=^5

bspc rule -a Feh desktop=^6
bspc rule -a Gpicview desktop=^6

bspc rule -a Thunar desktop=^7

bspc rule -a Evince desktop=^8
bspc rule -a calibre desktop=^8
bspc rule -a Zathura:zathura desktop=^8 state=tiled

bspc rule -a Lxappearance desktop=^9
bspc rule -a Nitrogen desktop=^9
bspc rule -a Pavucontrol:pavucontrol desktop=^9 follow=on
bspc rule -a Zeal:zeal desktop ^9 follow=on
bspc rule -a Libreoffice desktop=^9

bspc rule -a VirtualBox desktop=^10
bspc rule -a Wireshark desktop=^10
bspc rule -a "Keepassx2" desktop=^10 follow=on
bspc rule -a Anki desktop=^10
bspc rule -a burp-StartBurp desktop='^10' follow=on
bspc rule -a discord desktop=^10
bspc rule -a "OWASP ZAP" desktop=^10 follow=on

bspc rule -a Dunst flag=sticky layer=above

if which polybar > /dev/null ; then
  ~/scripts/toggle_polybar
elif which lemonbar > /dev/null ; then
  ~/scripts/toggle_panel.sh
fi
