#!/bin/sh

# NOTE: Use full paths to scripts. Otherwise the call from bspwmrc won't be able
# to use them.

PANEL_WM_NAME=bspwm_panel
PANEL_FIFO="/tmp/panel-fifo"
PANEL_HEIGHT=35
PANEL_WIDTH=1850
PANEL_X=35
PANEL_Y=5
PANEL_UNDERLINE=4

# NOTE: to find fonts use 'xlsfonts'
PANEL_FONT_FAMILY="-misc-hack-medium-r-normal--14-*-*-*-m-*-*-*"
ICON_FONT=""
# ICON_FONT="-misc-icons-medium-r-normal--16-*-*-*-p-*-iso10646-1"
ICON_FONT2="-misc-fontawesome-medium-r-normal--16-*-*-*-p-*-iso10646-1"
ICON_FONT3="-misc-symbola-medium-r-semicondensed--16-*-*-*-p-*-iso10646-1"

export PANEL_FIFO PANEL_HEIGHT PANEL_UNDERLINE PANEL_FONT_FAMILY PANEL_WM_NAME

# setup {{{
if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &

# }}}

# clock {{{
while true;
  do
    echo 'C' $(date +"%R %a %d");
  sleep 5;
done > "$PANEL_FIFO" &

# }}}

# battery {{{
while true;
do
  # NOTE: not sure if the system switched the battery numbers or something but
  # I had to change BAT0 to look for Battery 1 and vice versa
  BAT0=$(acpi | grep "Battery 1")
  BAT1=$(acpi | grep "Battery 0")

  state0=$(echo $BAT0 | cut -d' ' -f3 | sed 's/,//')
  state1=$(echo $BAT1 | cut -d' ' -f3 | sed 's/,//')

  if [ "$state0" == "Unknown" ]
  then
    BAT_CHARGING_ICON=''
    BAT_NORMAL_ICON=''
    BAT_LEVEL=$(echo $BAT0 | cut -d' ' -f4 | sed 's/,//')

    if [ "$(cat /tmp/panel.bat.full)" == "0" ] && [ "$BAT_LEVEL" == "94%" ]; then
      /usr/bin/notify-send "Battery Fully Charged" "Battery at 100%. Please stop charging."
      echo "1" > /tmp/panel.bat.full
    fi
    echo "B$BAT_CHARGING_ICON $BAT_LEVEL FULL"
  else
    if [ "$state0" == "Discharging" ]
    then
      BAT_LEVEL=$(echo $BAT0 | cut -d' ' -f4 | sed 's/,//')
      TIME_REMAINING=$(echo $BAT0 | cut -d',' -f3 | egrep -o "[0-9:]+")
      BAT_SYM="B$BAT_NORMAL_ICON"
    elif [ "$state0" == "Charging" ]
    then
      BAT_LEVEL=$(echo $BAT0 | cut -d' ' -f4 | sed 's/,//')
      TIME_REMAINING=$(echo $BAT0 | cut -d',' -f3 | egrep -o "[0-9:]+")
      BAT_SYM="B$BAT_CHARGING_ICON"
    elif [ "$state1" == "Discharging" ]
    then
      BAT_LEVEL=$(echo $BAT1 | cut -d' ' -f4 | sed 's/,//')
      TIME_REMAINING=$(echo $BAT1 | cut -d',' -f3 | egrep -o "[0-9:]+)")
      BAT_SYM="B$BAT_NORMAL_ICON"
    elif [ "$state1" == "Charging" ]
    then
      BAT_LEVEL=$(echo $BAT1 | cut -d' ' -f4 | sed 's/,//')
      TIME_REMAINING=$(echo $BAT1 | cut -d',' -f3 | egrep -o "[0-9:]+")
      BAT_SYM="B$BAT_CHARGING_ICON"
    fi
    echo $BAT_SYM $BAT_LEVEL $TIME_REMAINING
  fi

  # Notification of Battery Levels
  BAT_LEVEL=$(echo $BAT_LEVEL | sed 's/%//')
  if (("$BAT_LEVEL" > 40)); then
    if (("$BAT_LEVEL" < 94)); then
      echo "0" > /tmp/panel.bat.full
    fi
    echo "0" > /tmp/panel.bat.med
    echo "0" > /tmp/panel.bat.low
    echo "0" > /tmp/panel.bat.crit
  elif (("$BAT_LEVEL" < 40)) && (("$BAT_LEVEL" > 30)); then
    if [ "$(cat /tmp/panel.bat.med)" == "0" ]; then
      /usr/bin/notify-send "Battery at $BAT_LEVEL%" "Battery levels are getting low"
      echo "1" > /tmp/panel.bat.med
    fi
  elif (("$BAT_LEVEL" < 25)) && (("$BAT_LEVEL" > 15)); then
    if [ "$(cat /tmp/panel.bat.low)" == "0" ]; then
      /usr/bin/notify-send -u critical "Low Battery - less than $BAT_LEVEL%" "Battery levels are critical\! Charge Immediately\!"
      echo "1" > /tmp/panel.bat.low
    fi
  elif (("$BAT_LEVEL" < 15)); then
    if [ "$(cat /tmp/panel.bat.crit)" == "0" ]; then
      /usr/bin/notify-send -u critical "LOW BATTERY - Battery below $BAT_LEVEL%" "CHARGE NOW BEFORE LAPTOP DEATH\!\!"
      echo "1" > /tmp/panel.bat.crit
    fi
  fi

  sleep 5;
done > "$PANEL_FIFO" &

# }}}

# volume {{{
while true;
do
  # NOTE: uncommented ALSA_VOLUME uses Master instead of PCM which doesn't seem to be as accurate
  # VOL_VALUE=$(amixer -c 1 get Master | grep 'Mono: Playback' | grep -o '...%' | sed 's/\[//' | sed 's/%//' | sed 's/ //')

  # NOTE: the command below was used to get volume from alsa before I started using PulseAudio
  # VOL_VALUE=$(amixer -c 1 get PCM | egrep -o "[0-9]+\%" | uniq | sed 's/%//')

  # NOTE: Can't use awk in /bin/sh
  # VOL_VALUE=$(awk -F"[][]" '{ print $2 }' <(amixer get Master | grep 'Front Left: Playback') | sed 's/%//')
  VOL_VALUE=$(amixer get Master | grep 'Front Left: Playback' | cut -d [ -f2 | sed 's/%]//')
  VOL_STATE=$(amixer -c 1 get Master | grep 'Mono: Playback' | grep -o '\[on]')

  if [ $VOL_STATE ]
  then
    if [ $VOL_VALUE -ge 75 ]
    then
      echo 'V' $VOL_VALUE
    elif [ $VOL_VALUE -gt 35 -a $VOL_VALUE -lt 75 ]
    then
      echo 'V' $VOL_VALUE
    elif [ $VOL_VALUE -gt 0 -a $VOL_VALUE -lt 35 ]
    then
      echo 'V' $VOL_VALUE
    elif [ $VOL_VALUE -eq 0 ]
    then
      echo 'V' $VOL_VALUE
    fi
  else
    echo 'V mute'
  fi
  sleep 0.1
done > $PANEL_FIFO &

# }}}

# wifi {{{
while true;
do
  WIFI_ICON=''
  WIFI_SSID=$(iw wlp3s0 link | grep 'SSID' | sed 's/SSID: //' | sed 's/\t//')
  # WIFI_IP=$(ifconfig wlp3s0 | grep "inet " | cut -d' ' -f10)

  if [ "$WIFI_SSID" != "" ]
  then
    # echo "L$WIFI_ICON $WIFI_SSID | $WIFI_IP"
    echo "L$WIFI_ICON $WIFI_SSID"
  else
    echo "L$WIFI_ICON D/C"
  fi
  sleep 10
done > $PANEL_FIFO &

# }}}

# power {{{
echo 'P' > $PANEL_FIFO &

# }}}

. ~/scripts/panel_colors

# bspwm examples/panel/panel_colors
# . ~/scripts/panel_colors2

# bspwm examples/panel/panel

~/scripts/panel_bar < "$PANEL_FIFO" | lemonbar \
  -a 32 \
  -n "$PANEL_WM_NAME" \
  -g x"$PANEL_HEIGHT" \
  -f "$PANEL_FONT_FAMILY" \
  -f "$ICON_FONT" \
  -f "$ICON_FONT2" \
  -f "$ICON_FONT3" \
  -F "$COLOR_FOREGROUND" \
  -B "$COLOR_BACKGROUND" \
  -u $PANEL_UNDERLINE | zsh &

# The fix to allow fullscreen over the panel+stalonetray is in toggle_panel.sh

wait
# vim:foldmethod=marker:foldlevel=0
