#!/bin/sh
#
. ~/scripts/panel_colors

num_mon=$(bspc query -M | wc -l)
PADDING=" "
OCCUPIED=""
FREE=""

while read -r line ; do
  case $line in
    C*)
      # clock output
      clock="%{A:~/scripts/popup_cal &:}$PADDING${line#?}$PADDING%{A}"
      # clock="$PADDING${line#?}$PADDING"
      ;;

    B*)
      # battery percent output
      battery="%{A:~/scripts/bat.sh &:}$PADDING${line#?}$PADDING%{A}"
      ;;
    T*)
      # xtitle output
      title="${line#?}"
      ;;

    V*)
      # volume
      volume="$PADDING${line#?}$PADDING"
      ;;
    L*)
      # wifi link
      wifi="$PADDING${line#?}$PADDING"
      ;;
    F*)
      # free space /home
      free="$PADDING${line#?}$PADDING"
      ;;
    P*)
      # power
      power="%{A1:~/scripts/popup_sys &:}%{A3:~/scripts/popup_power &:}$PADDING${line#?}$PADDING%{A}%{A}"
      ;;

    W*)
      # bspwm internal state
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          M*)
            # active monitor
            if [ $num_mon -gt 1 ] ; then
              wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
            fi
            ;;
          m*)
            # inactive monitor
            if [ $num_mon -gt 1 ] ; then
              wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
            fi
            ;;
          O*)
            # focused occupied desktop
            wm_infos="${wm_infos}%{F$COLOR_BASE16_BLUE}%{U$COLOR_BASE16_BLUE}%{+u}$PADDING$OCCUPIED$PADDING%{-u}%{F-}"
            ;;
          F*)
            # focused free desktop
            wm_infos="${wm_infos}%{F$COLOR_BASE16_BLUE}%{U$COLOR_BASE16_BLUE}%{+u}$PADDING$FREE$PADDING%{-u}%{F-}"
            ;;
          U*)
            # focused urgent desktop
            wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
            ;;
          o*)
            # occupied desktop
            wm_infos="${wm_infos}%{F$COLOR_BASE16_WHITE}%{B$COLOR_OCCUPIED_BG}%{A:bspc desktop -f ${name}:}$PADDING$OCCUPIED$PADDING%{A}%{B-}%{F-}"
            ;;
          f*)
            # free desktop
            wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}%{A:bspc desktop -f ${name}:}$PADDING$FREE$PADDING%{A}%{B-}%{F-}"
            ;;
          u*)
            # urgent desktop
            wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}$PADDING${name}$PADDING%{B-}%{F-}"
            ;;
        esac
        shift
      done
      ;;
  esac
  printf "%s\n" "%{l}$PADDING$PADDING%{c}${wm_infos}%{r}${wifi}${battery}${date}${clock}${volume}%{F$COLOR_BASE16_WHITE}%{B$COLOR_BASE16_BLUE}${power}%{B-}%{F-}"
done
