#!/bin/bash

if [ "$(pgrep dzen2)" = "" ]
then
    swidth="$(xdpyinfo | grep  -oP " dimensions: +\K[0-9]+(?=x[0-9]+.*)")"
    width="240"
    offset="10"
    y="40"
    today=$(expr `date +'%d'` + 0)
    if [ $today -eq 1 ]
    then
      cal | sed "s/ \($today\) /^fg(#242427)^bg(#f3f3f3) \1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"

    elif [ $today -eq 2 ]
    then
      cal | sed "s/ \($today\) /^fg(#242427)^bg(#f3f3f3) \1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"
    elif [ $today -eq 3 ]
    then
      cal | sed "s/ \($today\) /^fg(#242427)^bg(#f3f3f3) \1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"
    elif [ $today -eq 4 ]
    then
      cal | sed "s/ \($today\) /^fg(#242427)^bg(#f3f3f3) \1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"
    elif [ $today -eq 5 ]
    then
      cal | sed "s/ \($today\) /^fg(#242427)^bg(#f3f3f3) \1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"
    elif [ $today -eq 6 ]
    then
      cal | sed "s/ \($today\) /^fg(#242427)^bg(#f3f3f3) \1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"
    elif [ $today -eq 7 ]
    then
      cal | sed "s/ \($today\) /^fg(#242427)^bg(#f3f3f3) \1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"
    elif [ $today -eq 8 ]
    then
      cal | sed "s/ \($today\) /^fg(#242427)^bg(#f3f3f3) \1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"
    elif [ $today -eq 9 ]
    then
      cal | sed "s/ \($today\) /^fg(#242427)^bg(#f3f3f3) \1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"
    else
      cal | sed "s/\($today\)/^fg(#242427)^bg(#f3f3f3)\1^fg()^bg()/g" | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 7 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"

    fi
else
    killall dzen2
fi
