#!/bin/bash

if ! pgrep dzen2 ; then
  swidth="$(xdpyinfo | grep  -oP " dimensions: +\K[0-9]+(?=x[0-9]+.*)")"
  width="200"
  offset="10"
  y="40"
  (
  echo "=Power Mode="
  echo "^ca(1,~/scripts/locker.sh & killall dzen2)Lock^ca()"
  echo "^ca(1,~/scripts/bspwm_logout)Logout^ca()"
  echo "^ca(1,systemctl reboot)Reboot^ca()"
  echo "^ca(1,systemctl poweroff)Poweroff^ca()"
  ) | dzen2 -p -x "$((swidth-width-offset))" -y "$y" -w "$width" -sa "c" -l 4 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#242427"
else
  killall dzen2
fi
