#!/bin/bash

# Script to add/remove todos to the todo list.
# NOTE: Can either use long opts or short opts, but not both.
# NOTE: Shortopt for -a, -r can only add/remove one todo at a time.
#       Long opts can add/remove 1+ todos at a time.

TODO_DIR="$HOME/.todo.d"

function help_msg() {
  echo "USAGE: todo [option] [todo|todo number]"
  echo "OPTIONS:"
  echo "  -h: print this message."
  echo "  -a: add a todo."
  echo "  -r: remove a todo."
  echo "  -l: list all todos."
  echo "  -c: clear all todos."
}

if (( $# < 1 )); then
  echo "ERROR: invalid number of arguments."
  help_msg
  exit 1
fi

# create the directory if it doesn't exist
if ! [ -d "$TODO_DIR" ]; then
  mkdir "$TODO_DIR"
fi

TODO_COUNT=$(ls $TODO_DIR | wc -l)

function add_todo () {
  if [ -z "$1" ]; then
    echo "ERROR: no todo supplied. please provide a todo."
    echo "USAGE: todo [add|--add|-a] [todo]"
    exit 2
  else
    todo_number=$(($(ls $TODO_DIR | sort -n | tail -n 1) + 1))
    for todo in "$@"
    do
      echo "$todo" > "$TODO_DIR/$todo_number"
      todo_number=$(($todo_number + 1))
    done
  fi
}

function remove_todo () {
  if [ -z "$1" ]; then
    echo "ERROR: no todo supplied. please provide a todo."
    echo "USAGE: todo [remove|--remove|-r] [todo]"
    exit 2
  fi

  for todo in $*
  do
    if [ -e "$TODO_DIR/$todo" ]; then
      rm -f "$TODO_DIR/$todo"
    else
      echo "ERROR: Cannot remove $todo. Todo does not exist."
      exit 3
    fi
  done

  reorder_todo
}

function reorder_todo () {
  # first=$(ls $TODO_DIR | sort -n | head -n 1)

  # In the case that we remove the first todo, then $first will be '2' or higher
  # Hence it will reorder from 2 to $last
  # In order to prevent this, if $first is greater than 1, set it to 1
  # if [ $first -gt 1 ]; then first=1; fi

  # NOTE: After thinking about it, first should always be 1.
  first=1
  last=$(ls $TODO_DIR | sort -n | tail -n 1)

  # Determine the missing files
  for todo in $(seq $first $last)
  do
    # Find the first missing todo
    if ! [ -e "$TODO_DIR/$todo" ]; then
      missing=$todo
      break
    fi
  done

  # Only reorder if $missing todos exist
  if ! [[ -z "$missing" ]]; then
    # Reorder/Re-number the todo files
    curr=$missing
    for todo in $(seq $missing $last)
    do
      if [ -e "$TODO_DIR/$todo" ]; then
        mv "$TODO_DIR/$todo" "$TODO_DIR/$curr"
        curr=$(($curr + 1))
      fi
    done
  fi
}

function clear_todo () {
  for todo in $TODO_DIR/*
  do
    rm -f $todo
  done
  echo "Todo list cleared."
}

function list_todo () {
  if (( $TODO_COUNT > 0 )); then
    echo "TODO LIST:"
    for todo in $(ls $TODO_DIR/ | sort -n)
    do
      todo_number=$(echo "$todo" | egrep -o "[0-9]+$")
      todo_content=$(cat "$TODO_DIR/$todo_number")
      echo "  $todo_number. $todo_content"
    done
  else
    echo "Nothing todo."
  fi
}

# Check for long opts first
case $1 in
  add|--add|-a)
    shift 1
    add_todo "$@"; exit 0
    ;;
  remove|--remove|-r)
    shift 1
    remove_todo "$@"
    exit 0
    ;;
  list|--list|-l)
    list_todo; exit 0
    ;;
  clear|--clear|-c)
    clear_todo; exit 0
    ;;
  help|--help|-h)
    help_msg; exit 0
    ;;
  reorder|reo*)
    reorder_todo; exit 0
    ;;
  *)
    echo "Invalid command: $1."
    exit 1
esac

# NOTE: not using getopts prefer using long opts. see above.
# while getopts ":a:cr:hl" opt; do
#   case $opt in
#     a)
#       add_todo "$OPTARG"
#       ;;
#     c)
#       clear_todo
#       ;;
#     r)
#       remove_todo "$OPTARG"
#       ;;
#     h)
#       help_msg
#       ;;
#     l)
#       list_todo
#       ;;
#     x)
#       reorder_todo
#       ;;
#     \?)
#       echo "Invalid option: -$OPTARG" >&2
#       help_msg
#       exit 4
#       ;;
#     :)
#       echo "Option -$OPTARG requires an argument." >&2
#       exit 5
#       ;;
#   esac
# done

exit 0
