#!/usr/bin/env bash

POLYBAR_HEIGHT=35
POLYBAR_WM_NAME="topbar"
POLYBAR_TRAY_NAME="Polybar tray window"

if ! pgrep polybar > /dev/null ; then
  bspc config top_padding $POLYBAR_HEIGHT && polybar top &> /tmp/polybar.log &

  # Sends tray & polybar to the layer below Bspwm root so fullscreen works properly.
  until tray_id=$(xdo id -a "$POLYBAR_TRAY_NAME")
  do
    sleep 0.5
  done
  [ -n "$tray_id" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$tray_id"

  until panel_id=$(xdo id -a "$POLYBAR_WM_NAME")
  do
    sleep 0.5
  done
  echo "$panel_id"
  [ -n "$panel_id" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$panel_id"
else
  killall polybar
  # Need to sleep to give time for polybar to die
  # otherwise top_padding fails
  sleep 1
  bspc config top_padding 0
fi

