alias up='cd ..'
alias vim='nvim'

if which terraform.exe >/dev/null; then
  alias terraform='terraform.exe'
fi

function git_add_commit_push() {
  git add . && git commit -m "$1"
  git push
}

if ! command -v git &> /dev/null; then
  if ! command -v sed &> /dev/null; then
    alias current_branch="git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||'"
  fi
  alias ga='git add'
  alias gacp='git_add_commit_push'
  alias gap='git add -p' # git add with interactive prompt
  alias gc='git commit'
  alias gcm='git commit -m'
  alias gco='git checkout'
  alias gd='git diff'
  alias gdh='git diff HEAD --'
  alias gl='git lg'
  alias glo='git log --oneline'
  alias gp='git push'
  alias gst='git status'
fi
